---
- name: Loading a task to install dependencies (Debian)
  ansible.builtin.include_tasks: setup-dependencies.yml
  when: ansible_os_family == "Debian"

- name: Loading a task to defined packages (Debian)
  ansible.builtin.include_tasks: setup-packages.yml
  when: ansible_os_family == "Debian"
