---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      dependencies:
        - "git"
        - "nano"
        - "unzip"
        - "curl"
        - "wget"
